# kind: Pod
# apiVersion: v1
# metadata:
#   name: chaos-exp
#   labels:
#     app: chaos
# spec:
#   containers:
#     - name: chaos-exp-app
#       image: suvadityamuk/chaos_exp

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: chaos-exp-deployment
  labels:
    app: chaos
spec:
  replicas: 4
  selector:
    matchLabels:
      app: chaos
  template:
    metadata:
      labels:
        app: chaos
    spec:
      containers:
        - name: chaos-exp-app
          image: suvadityamuk/chaos_exp

---

kind: Service
apiVersion: v1
metadata:
  name: chaos-target-service
spec:
  selector:
    app: chaos
  ports:
    - port: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaos-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: chaos-target-service
           port:
            number: 5000